<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Afghanistan',
                'iso2' => 'AF',
                'iso3' => 'AFG',
                'phone_code' => '93',
                'capital' => 'Kabul',
                'currency' => 'AFN',
                'currency_symbol' => '؋',
                'flag' => '🇦🇫',
                'status' => true,
            ],
            [
                'name' => 'Albania',
                'iso2' => 'AL',
                'iso3' => 'ALB',
                'phone_code' => '355',
                'capital' => 'Tirana',
                'currency' => 'ALL',
                'currency_symbol' => 'L',
                'flag' => '🇦🇱',
                'status' => true,
            ],
            [
                'name' => 'Algeria',
                'iso2' => 'DZ',
                'iso3' => 'DZA',
                'phone_code' => '213',
                'capital' => 'Algiers',
                'currency' => 'DZD',
                'currency_symbol' => 'دج',
                'flag' => '🇩🇿',
                'status' => true,
            ],
            [
                'name' => 'Andorra',
                'iso2' => 'AD',
                'iso3' => 'AND',
                'phone_code' => '376',
                'capital' => 'Andorra la Vella',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇦🇩',
                'status' => true,
            ],
            [
                'name' => 'Angola',
                'iso2' => 'AO',
                'iso3' => 'AGO',
                'phone_code' => '244',
                'capital' => 'Luanda',
                'currency' => 'AOA',
                'currency_symbol' => 'Kz',
                'flag' => '🇦🇴',
                'status' => true,
            ],
            [
                'name' => 'Argentina',
                'iso2' => 'AR',
                'iso3' => 'ARG',
                'phone_code' => '54',
                'capital' => 'Buenos Aires',
                'currency' => 'ARS',
                'currency_symbol' => '$',
                'flag' => '🇦🇷',
                'status' => true,
            ],
            [
                'name' => 'Armenia',
                'iso2' => 'AM',
                'iso3' => 'ARM',
                'phone_code' => '374',
                'capital' => 'Yerevan',
                'currency' => 'AMD',
                'currency_symbol' => '֏',
                'flag' => '🇦🇲',
                'status' => true,
            ],
            [
                'name' => 'Australia',
                'iso2' => 'AU',
                'iso3' => 'AUS',
                'phone_code' => '61',
                'capital' => 'Canberra',
                'currency' => 'AUD',
                'currency_symbol' => '$',
                'flag' => '🇦🇺',
                'status' => true,
            ],
            [
                'name' => 'Austria',
                'iso2' => 'AT',
                'iso3' => 'AUT',
                'phone_code' => '43',
                'capital' => 'Vienna',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇦🇹',
                'status' => true,
            ],
            [
                'name' => 'Azerbaijan',
                'iso2' => 'AZ',
                'iso3' => 'AZE',
                'phone_code' => '994',
                'capital' => 'Baku',
                'currency' => 'AZN',
                'currency_symbol' => '₼',
                'flag' => '🇦🇿',
                'status' => true,
            ],
            [
                'name' => 'United States',
                'iso2' => 'US',
                'iso3' => 'USA',
                'phone_code' => '1',
                'capital' => 'Washington, D.C.',
                'currency' => 'USD',
                'currency_symbol' => '$',
                'flag' => '🇺🇸',
                'status' => true,
            ],
            [
                'name' => 'Brazil',
                'iso2' => 'BR',
                'iso3' => 'BRA',
                'phone_code' => '55',
                'capital' => 'Brasília',
                'currency' => 'BRL',
                'currency_symbol' => 'R$',
                'flag' => '🇧🇷',
                'status' => true,
            ],
            [
                'name' => 'Canada',
                'iso2' => 'CA',
                'iso3' => 'CAN',
                'phone_code' => '1',
                'capital' => 'Ottawa',
                'currency' => 'CAD',
                'currency_symbol' => '$',
                'flag' => '🇨🇦',
                'status' => true,
            ],
            [
                'name' => 'China',
                'iso2' => 'CN',
                'iso3' => 'CHN',
                'phone_code' => '86',
                'capital' => 'Beijing',
                'currency' => 'CNY',
                'currency_symbol' => '¥',
                'flag' => '🇨🇳',
                'status' => true,
            ],
            [
                'name' => 'France',
                'iso2' => 'FR',
                'iso3' => 'FRA',
                'phone_code' => '33',
                'capital' => 'Paris',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇫🇷',
                'status' => true,
            ],
            [
                'name' => 'Germany',
                'iso2' => 'DE',
                'iso3' => 'DEU',
                'phone_code' => '49',
                'capital' => 'Berlin',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇩🇪',
                'status' => true,
            ],
            [
                'name' => 'India',
                'iso2' => 'IN',
                'iso3' => 'IND',
                'phone_code' => '91',
                'capital' => 'New Delhi',
                'currency' => 'INR',
                'currency_symbol' => '₹',
                'flag' => '🇮🇳',
                'status' => true,
            ],
            [
                'name' => 'Italy',
                'iso2' => 'IT',
                'iso3' => 'ITA',
                'phone_code' => '39',
                'capital' => 'Rome',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇮🇹',
                'status' => true,
            ],
            [
                'name' => 'Japan',
                'iso2' => 'JP',
                'iso3' => 'JPN',
                'phone_code' => '81',
                'capital' => 'Tokyo',
                'currency' => 'JPY',
                'currency_symbol' => '¥',
                'flag' => '🇯🇵',
                'status' => true,
            ],
            [
                'name' => 'Mexico',
                'iso2' => 'MX',
                'iso3' => 'MEX',
                'phone_code' => '52',
                'capital' => 'Mexico City',
                'currency' => 'MXN',
                'currency_symbol' => '$',
                'flag' => '🇲🇽',
                'status' => true,
            ],
            [
                'name' => 'Russia',
                'iso2' => 'RU',
                'iso3' => 'RUS',
                'phone_code' => '7',
                'capital' => 'Moscow',
                'currency' => 'RUB',
                'currency_symbol' => '₽',
                'flag' => '🇷🇺',
                'status' => true,
            ],
            [
                'name' => 'South Korea',
                'iso2' => 'KR',
                'iso3' => 'KOR',
                'phone_code' => '82',
                'capital' => 'Seoul',
                'currency' => 'KRW',
                'currency_symbol' => '₩',
                'flag' => '🇰🇷',
                'status' => true,
            ],
            [
                'name' => 'Spain',
                'iso2' => 'ES',
                'iso3' => 'ESP',
                'phone_code' => '34',
                'capital' => 'Madrid',
                'currency' => 'EUR',
                'currency_symbol' => '€',
                'flag' => '🇪🇸',
                'status' => true,
            ],
            [
                'name' => 'United Kingdom',
                'iso2' => 'GB',
                'iso3' => 'GBR',
                'phone_code' => '44',
                'capital' => 'London',
                'currency' => 'GBP',
                'currency_symbol' => '£',
                'flag' => '🇬🇧',
                'status' => true,
            ],
        ];

        foreach ($countries as $country) {
            // Use iso2 as the unique key so seeder is idempotent
            DB::table('countries')->updateOrInsert(
                [
                    'iso2' => $country['iso2'],
                ],
                [
                    'id' => Str::uuid(),
                    'name' => $country['name'],
                    'iso3' => $country['iso3'],
                    'phone_code' => $country['phone_code'],
                    'capital' => $country['capital'],
                    'currency' => $country['currency'],
                    'currency_symbol' => $country['currency_symbol'],
                    'flag' => $country['flag'],
                    'status' => $country['status'],
                ]
            );
        }
    }
}
