<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Medical Letter</title>
    <style>
        @page {
            margin: 40px 50px;
        }

        body {
            font-family: Helvetica, Arial, sans-serif;
            font-size: 11pt;
            color: #000;
            line-height: 1.6;
        }

        /* Header */
        .header {
            margin-bottom: 30px;
        }

        .hospital-name {
            font-size: 14pt;
            font-weight: bold;
            text-transform: uppercase;
        }

        .hospital-address {
            font-size: 10pt;
            margin-top: 3px;
        }

        .hospital-contact {
            font-size: 10pt;
        }

        /* Title */
        .letter-title {
            text-align: center;
            font-size: 12pt;
            font-weight: bold;
            margin: 25px 0;
            text-transform: uppercase;
        }

        /* Recipient */
        .recipient {
            margin-bottom: 20px;
        }

        /* Body */
        .content {
            text-align: left;
        }

        /* Signature */
        .signature {
            margin-top: 40px;
        }

        .doctor-name {
            font-weight: bold;
            margin-top: 10px;
        }

        /* Footer */
        .footer {
            position: fixed;
            bottom: 30px;
            left: 50px;
            right: 50px;
            font-size: 8pt;
            color: #444;
            border-top: 1px solid #ccc;
            padding-top: 8px;
        }

        .powered {
            margin-top: 10px;
            font-size: 8pt;
            color: #777;
            text-align: center;
        }
    </style>
</head>

<body>

    <!-- Header -->
    <div class="header">
        <div class="row align-items-center justify-content-between">
        <div class="hospital-name">
            {{ $hospital['name'] ?? 'AKRA HEALTH' }}
        </div>
        <div class="hospital-address">
            {{ $hospital['address'] ?? '' }}
            <br>
            {{ $hospital['city'] ?? '' }}{{ !empty($hospital['city']) && !empty($hospital['state']) ? ', ' : '' }}{{ $hospital['state'] ?? '' }}
            <br>
            {{ $hospital['zip'] ?? '' }}
        </div>
        <div class="hospital-contact">
            @php
                $contacts = array_filter([
                    !empty($hospital['phone']) ? 'Phone: ' . $hospital['phone'] : null,
                    !empty($hospital['email']) ? 'Email: ' . $hospital['email'] : null,
                ]);
            @endphp
            {{ implode(' | ', $contacts) }}
        </div>
        <img src="{{ $logo ?? '' }}" style="max-width:120px;">
        </div>
    </div>

    <!-- Title -->
    <div class="letter-title">
        Letter
        <hr>
    </div>

    <!-- Recipient -->
    <div class="recipient">
        {{ $to ?? '' }}<br>
        {{ $recipient_address['address_1'] }},{{ $recipient_address['address_2'] }}
        <br>
        {{ $recipient_address['city'] }},{{ $recipient_address['state'] }}
        <br>
        {{ $recipient_address['zip'] }}
        <br><br>
        <strong>Dear {{ $to ?? 'Sir/Madam' }},</strong>
    </div>

    <!-- Content -->
    <div class="content">
        {!! $body !!}
    </div>

    <!-- Signature -->
    <div class="signature">
        Sincerely,<br><br>

        @if (!empty($signature))
            <img src="{{ $signature }}" style="max-width:120px;"><br>
        @endif

        <div class="doctor-name">
            {{ $doctor['name'] ?? 'Demo Doctor' }}
        </div>
    </div>

    <!-- Footer -->
    <div class="footer">
        CONFIDENTIALITY NOTICE: The information contained in this document is intended only
        for the recipient named above. Unauthorized use, copying, or distribution is prohibited.
        <div class="powered">
            This document was generated by {{ $hospital['name'] ?? 'AKRA HEALTH' }}
        </div>
    </div>

</body>

</html>
