<?php

namespace App\Http\Controllers\Doctor;

use App\Http\Controllers\Controller;
use App\Http\Requests\LabOrderRequest;
use App\Models\Order;
use App\Services\OrderService;
use Barryvdh\DomPDF\Facade\Pdf;

class EncounterOrderController extends Controller
{
    public $order;

    use \App\Traits\CommonTrait;

    public function __construct(OrderService $order)
    {
        $this->order = $order;
    }

    /**
     * upsert
     *
     * @param  mixed  $request
     * @return void
     */
    public function upsert(LabOrderRequest $request)
    {
        return $this->order->upsertOrder($request->all());
    }

    public function downloadOrderPdf($id)
    {
        try {
            $order = Order::findOrFail($id);
            $patientId = $order->patient_id;
            $pageData = $this->page_order($id, $patientId);

            if (empty($pageData)) {
                throw new \Exception('No order data found');
            }

            $html = view('pdf.order', $pageData)->render();
            $filename = 'order_'.$id.'.pdf';

            // Debug: Check if HTML is generated
            \Log::info('HTML generated, length: '.strlen($html));

            $pdf = Pdf::loadHTML($html)
                ->setPaper('a4')
                ->setOption('isHtml5ParserEnabled', true);

            $dompdf = $pdf->getDomPDF();
            $dompdf->set_option('isRemoteEnabled', true);
            $dompdf->set_option('chroot', public_path());
            $pdf->setBasePath(public_path());

            // Render PDF
            $dompdf->render();

            $canvas = $dompdf->get_canvas();

            $canvasWidth = $canvas->get_width();
            $canvasHeight = $canvas->get_height();
            $footerY = $canvasHeight - 100;  // slightly higher so it matches your screenshot style

            $footer_text_1 = "CONFIDENTIALITY NOTICE: The information contained in this document or facsimile transmission is intended for the recipient named above. If you are not the intended recipient or the intended recipient's agent, you are hereby notified that dissemination, copying, or distribution of the information contained in the transmission is prohibited. If you are not the intended recipient, please notify us immediately by telephone and return the documents to us by mail. Thank you.";
            $footer_text_2 = "\nThis document was generated by AKRA TELEHEALTH.";

            // Center align the footer text
            $font = 'Helvetica';
            $font_size = 8;
            $line_spacing = 12;

            // ---------- Print First Paragraph ----------
            $paragraphY = $footerY + 18;

            $lines = explode("\n", wordwrap($footer_text_1, 150));
            foreach ($lines as $line) {
                $text_width = $canvas->get_text_width($line, $font, $font_size);
                $x = ($canvasWidth - $text_width) / 2;
                $canvas->text($x, $paragraphY, $line, $font, $font_size);
                $paragraphY += $line_spacing;
            }

            // ---------- Print Second Line ----------
            $text_width_end = $canvas->get_text_width($footer_text_2, $font, $font_size);
            $x_end = ($canvasWidth - $text_width_end) / 2;
            $canvas->text($x_end, $paragraphY + 5, $footer_text_2, $font, $font_size);
            $canvas->line(20, $footerY, $canvas->get_width() - 10, $footerY, [0, 0, 0], 1);
            // Page Numbers
            $canvas->page_text(
                $canvasWidth - 100,
                $canvasHeight - 30,
                'Page {PAGE_NUM} of {PAGE_COUNT}',
                'Helvetica',
                8,
                [0, 0, 0]
            );
            // Save File
            file_put_contents($filename, $dompdf->output());

            return $pdf->download($filename);
        } catch (\Exception $e) {
            \Log::error('PDF download failed: '.$e->getMessage());

            // Return a simple error response that works with downloads
            return response('PDF Generation Failed: '.$e->getMessage(), 500)
                ->header('Content-Type', 'text/plain');
        }
    }

    /**
     * getOrders
     *
     * @param  mixed  $encounter_id
     * @param  mixed  $field
     * @return void
     */
    public function getOrders($encounter_id, $field)
    {
        return Order::where('encounter_id', $encounter_id)->whereNotNull($field)->get();
    }

    /**
     * delete
     *
     * @param  mixed  $id
     * @param  mixed  $field
     * @return void
     */
    public function delete($id, $field)
    {
        $order = Order::where('id', $id)->first();
        $encounter_id = $order->encounter_id;
        $order->delete();

        return $this->getOrders($encounter_id, $field);
    }
}
