<?php

return [
    'Pharmacy',
    'School',
    'Office',
    'Home',
    'Assisted Living Facility',
    'Group Home',
    'Mobile Unit',
    'Temporary Lodging',
    'Walk-in Retail Health Clinic',
    'Urgent Care Facility',
    'Inpatient Hospital',
    'Outpatient Hospital',
    'Emergency Room - Hospital',
    'Ambulatory Surgical Center',
    'Birthing Center',
    'Military Treatment Facility',
    'Skilled Nursing Facility',
    'Nursing Facility',
    'Ambulance - Land',
    'Ambulance - Air or Water',
    'Independent Clinic',
    'Federally Qualified Health Center',
    'Intermediate Care Facility',
    'Mass Immunization Center',
    'Public Health Clinic',
    'Rural Health Clinic',
    'Other Place of Service',
];
