<?php

return [
    'Body cavity route',
    'Buccal route',
    'Caudal route',
    'Colostomy route',
    'Conjunctival route',
    'Cutaneous route',
    'Dental use',
    'Digestive tract route',
    'Endocervical use',
    'Endosinusial use',
    'Endotracheopulmonary use',
    'Enteral route',
    'Epidural route',
    'Esophagoscope route',
    'Extra-amniotic use',
    'Extracorporeal route',
    'Fistula route',
    'Gastro-intestinal stoma route',
    'Gastroenteral use',
    'Gastrostomy route',
    'Gingival use',
    'Ileostomy route',
    'Infiltration route',
    'Interstitial route',
    'Intra-arterial route',
    'Intra-articular route',
    'Intraabdominal route',
    'Intraamniotic use',
    'Intrabiliary route',
    'Intrabronchial route',
    'Intrabursal use',
    'Intracameral route',
    'Intracardiac use',
    'Intracartilaginous route',
    'Intracavernous use',
    'Intracerebral route',
    'Intracerebroventricular route',
    'Intracisternal route',
    'Intracolonic route',
    'Intracorneal route',
    'Intracoronal route',
    'Intracoronary use',
    'Intracorpus cavernosum route',
    'Intracranial route',
    'Intradermal use',
    'Intradiscal use',
    'Intraductal route',
    'Intraduodenal route',
    'Intradural route',
    'Intraepicardial route',
    'Intraepidermal route',
    'Intraesophageal route',
    'Intragastric route',
    'Intragingival route',
    'Intrahepatic route',
    'Intraileal route',
    'Intrajejunal route',
    'Intralesional use',
    'Intralingual route',
    'Intraluminal route',
    'Intralymphatic use',
    'Intramammary route',
    'Intramedullary route',
    'Intrameningeal route',
    'Intramural route',
    'Intramuscular route',
    'Intramyometrial route',
    'Intraneural route',
    'Intraocular use',
    'Intraosseous route',
    'Intraovarian route',
    'Intrapericardial route',
    'Intraperitoneal route',
    'Intrapleural use',
    'Intraprostatic route',
    'Intrapulmonary route',
    'Intrasinal route',
    'Intraspinal route',
    'Intrasternal use',
    'Intrasynovial route',
    'Intratendinous route',
    'Intratesticular route',
    'Intrathecal route',
    'Intrathoracic route',
    'Intratracheal route',
    'Intratumor route',
    'Intratympanic route',
    'Intrauterine route',
    'Intravascular route',
    'Intravenous central route',
    'Intravenous peripheral route',
    'Intravenous route',
    'Intraventricular route - cardiac',
    'Intravesical use',
    'Intravitreal route',
    'Jejunostomy route',
    'Laryngeal route',
    'Lower respiratory tract route',
    'Mucous fistula route',
    'Nasal route',
    'Nasoduodenal route',
    'Nasogastric route',
    'Nasojejunal route',
    'Ophthalmic route',
    'Oral route',
    'Orogastric route',
    'Oromucosal use',
    'Oropharyngeal route',
    'Otic route',
    'Paracervical route',
    'Paravertebral route',
    'Per rectum',
    'Per vagina',
    'Percutaneous route',
    'Periarticular use',
    'Peribulbar route',
    'Peridural route',
    'Perineural use',
    'Periodontal route',
    'Periosteal route',
    'Peritendinous route',
    'Periurethral route',
    'Respiratory tract route',
    'Retrobulbar route',
    'Subconjunctival use',
    'Subcutaneous route',
    'Subgingival route',
    'Sublesional route',
    'Sublingual route',
    'Submucosal route',
    'Suborbital route',
    'Subtendinous route',
    'Surgical cavity route',
    'Surgical drain route',
    'Topical route',
    'Transcervical route',
    'Transdermal route',
    'Transendocardial route',
    'Transmucosal route',
    'Transplacental route',
    'Transtracheal route',
    'Transtympanic route',
    'Transurethral route',
    'Tumor cavity route',
    'Ureteral route',
    'Urethral route',
    'Urostomy route',
];
