<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Education Material</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px 20px;
        }
        
        .header {
            border-bottom: 2px solid #6f42c1;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        
        .header h1 {
            color: #6f42c1;
            font-size: 24px;
            margin-bottom: 10px;
        }
        
        .header .date {
            color: #666;
            font-size: 14px;
        }
        
        .content {
            background: #f9f9f9;
            border-radius: 8px;
            padding: 30px;
            margin-bottom: 20px;
        }
        
        .content h2 {
            color: #333;
            font-size: 20px;
            margin-bottom: 15px;
        }
        
        .content p {
            margin-bottom: 15px;
            text-align: justify;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            font-size: 12px;
            color: #999;
            text-align: center;
        }
        
        .disclaimer {
            background: #fff3cd;
            border: 1px solid #ffc107;
            border-radius: 4px;
            padding: 15px;
            margin: 20px 0;
            font-size: 14px;
        }
        
        .disclaimer strong {
            color: #856404;
        }
        
        @media print {
            body {
                padding: 0;
            }
            
            .content {
                background: none;
                padding: 0;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $topic }}</h1>
        <p class="date">Generated on: {{ $date }}</p>
    </div>
    
    <div class="content">
        <h2>Patient Education Material</h2>
        
        @if($description)
            <p>{!! nl2br(e($description)) !!}</p>
        @else
            <p>
                This patient education material provides important health information for your reference.
                Please review this information and discuss any questions or concerns with your healthcare provider.
            </p>
        @endif
        
        <div class="disclaimer">
            <strong>Disclaimer:</strong> This information is provided for educational purposes only and is not intended 
            as a substitute for professional medical advice, diagnosis, or treatment. Always consult with your 
            healthcare provider regarding any medical condition or treatment decisions.
        </div>
    </div>
    
    <div class="footer">
        <p>Generated by Akra Health System</p>
        <p>{{ now()->year }} All Rights Reserved</p>
    </div>
</body>
</html>

